# Generated by Django 4.0.3 on 2022-03-07 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Services', '0003_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Testimonials',
        ),
    ]
