# Generated by Django 4.0.3 on 2022-03-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_rename_review_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
