# Generated by Django 4.0.3 on 2022-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_service_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
