# Generated by Django 4.0.3 on 2022-03-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
