# Generated by Django 4.0.3 on 2022-03-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_service_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='specialist',
        ),
    ]
