# Generated by Django 4.0.3 on 2022-03-06 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='profile_img',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='verified_user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Common.configchoice'),
        ),
    ]
