# Generated by Django 4.0.3 on 2022-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_myuser_profile_alter_myuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=25)),
                ('message', models.TextField()),
            ],
        ),
    ]
