# Generated by Django 4.0.3 on 2022-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_myuser_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='about')),
                ('cover', models.ImageField(upload_to='about')),
                ('description', models.TextField()),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(max_length=20)),
            ],
        ),
    ]
