# Generated by Django 4.0.3 on 2022-03-06 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='ktm', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
