# Generated by Django 4.0.3 on 2022-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_alter_myuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=8799, max_length=200),
            preserve_default=False,
        ),
    ]
