# Generated by Django 4.0.3 on 2022-03-13 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_remove_service_specialist'),
        ('Accounts', '0014_alter_myuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.service'),
        ),
    ]
