# Generated by Django 4.0.3 on 2022-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_myuser_on_leave_myuser_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
