# Generated by Django 4.0.3 on 2022-03-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_myuser_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='is_delete',
        ),
    ]
