# Generated by Django 4.0.3 on 2022-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_rename_appointment_time_order_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_complete',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
