# Generated by Django 4.0.3 on 2022-03-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_payment_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
